CREATE TABLE players_22 (
    sofifa_id INT NOT NULL PRIMARY KEY,                  -- primary key (unique identifier)
    player_url VARCHAR(255),                             -- URL in string format
    short_name VARCHAR(100),                             --  (short player name)
    long_name VARCHAR(255),                              --  (full player name)
    player_positions VARCHAR(255),                       --  (positions player can play)
    overall INT,                                         --  (player overall rating)
    potential INT,                                       --  (player potential rating)
    value_eur INT,                                       --  (player value in euros)
    wage_eur INT,                                        --  (player wage in euros)
    age INT,                                             --  (player age)
    dob DATE,                                            --  (date of birth)
    height_cm INT,                                       --  (height in cm)
    weight_kg INT,                                       --  (weight in kg)
    club_team_id INT,                                    --  (ID of the club team)
    club_name VARCHAR(255),                              --  (club name)
    league_name VARCHAR(255),                            --  (league name)
    league_level INT,                                    --  (league level)
    club_position VARCHAR(50),                           --  (player position at the club)
    club_jersey_number INT,                              --  (player's jersey number)
    club_loaned_from VARCHAR(255),                       --  (if player is loaned from another club)
    club_joined VARCHAR(255),                                    -- Date (date the player joined the club)
    club_contract_valid_until VARCHAR(255),                      -- Date (contract expiry date)
    nationality_id INT,                                  --  (ID of the player's nationality)
    nationality_name VARCHAR(100),                       --  (player's nationality)
    nation_team_id INT,                                  --  (ID of the national team)
    nation_position VARCHAR(50),                         --  (position in national team)
    nation_jersey_number INT,                            --  (jersey number in national team)
    preferred_foot VARCHAR(20),                          --  (preferred foot, e.g., "Left" or "Right")
    weak_foot INT,                                       --  (weak foot rating)
    skill_moves INT,                                     --  (skill moves rating)
    international_reputation INT,                        --  (international reputation rating)
    work_rate VARCHAR(50),                               --  (player's work rate)
    body_type VARCHAR(50),                               --  (player's body type)
    real_face VARCHAR(50),                               --  (whether player has a real face)
    release_clause_eur INT,                              --  (release clause in euros)
    player_tags TEXT,                                    --  (tags related to the player)
    player_traits TEXT,                                  --  (traits of the player)
    pace INT,                                            --  (pace rating)
    shooting INT,                                        --  (shooting rating)
    passing INT,                                         --  (passing rating)
    dribbling INT,                                       --  (dribbling rating)
    defending INT,                                       --  (defending rating)
    physic INT,                                          --  (physic rating)
    attacking_crossing INT,                              --  (attacking crossing rating)
    attacking_finishing INT,                             --  (attacking finishing rating)
    attacking_heading_accuracy INT,                      --  (heading accuracy rating)
    attacking_short_passing INT,                         --  (short passing rating)
    attacking_volleys INT,                               --  (volleys rating)
    skill_dribbling INT,                                 --  (dribbling skill rating)
    skill_curve INT,                                     --  (curve skill rating)
    skill_fk_accuracy INT,                               --  (free kick accuracy rating)
    skill_long_passing INT,                              --  (long passing skill rating)
    skill_ball_control INT,                              --  (ball control skill rating)
    movement_acceleration INT,                           --  (movement acceleration rating)
    movement_sprint_speed INT,                           --  (movement sprint speed rating)
    movement_agility INT,                                --  (movement agility rating)
    movement_reactions INT,                              --  (movement reactions rating)
    movement_balance INT,                                --  (movement balance rating)
    power_shot_power INT,                                --  (shot power rating)
    power_jumping INT,                                   --  (jumping power rating)
    power_stamina INT,                                   --  (stamina power rating)
    power_strength INT,                                  --  (strength power rating)
    power_long_shots INT,                                --  (long shots power rating)
    mentality_aggression INT,                            --  (aggression mentality rating)
    mentality_interceptions INT,                         --  (interceptions mentality rating)
    mentality_positioning INT,                           --  (positioning mentality rating)
    mentality_vision INT,                                --  (vision mentality rating)
    mentality_penalties INT,                             --  (penalties mentality rating)
    mentality_composure INT,                             --  (composure mentality rating)
    defending_marking_awareness INT,                     --  (marking awareness rating)
    defending_standing_tackle INT,                       --  (standing tackle rating)
    defending_sliding_tackle INT,                        --  (sliding tackle rating)
    goalkeeping_diving INT,                              --  (goalkeeping diving rating)
    goalkeeping_handling INT,                            --  (goalkeeping handling rating)
    goalkeeping_kicking INT,                             --  (goalkeeping kicking rating)
    goalkeeping_positioning INT,                         --  (goalkeeping positioning rating)
    goalkeeping_reflexes INT,                            --  (goalkeeping reflexes rating)
    goalkeeping_speed INT,                               --  (goalkeeping speed rating)
    ls VARCHAR(50),                                              --  (left striker rating)
    st VARCHAR(50),                                              --  (center striker rating)
    rs VARCHAR(50),                                              --  (right striker rating)
    lw VARCHAR(50),                                              --  (left wing rating)
    lf VARCHAR(50),                                              --  (left forward rating)
    cf VARCHAR(50),                                              --  (center forward rating)
    rf VARCHAR(50),                                              --  (right forward rating)
    rw VARCHAR(50),                                              --  (right wing rating)
    lam VARCHAR(50),                                             --  (left attacking midfielder rating)
    cam VARCHAR(50),                                             --  (center attacking midfielder rating)
    ram VARCHAR(50),                                             --  (right attacking midfielder rating)
    lm VARCHAR(50),                                              --  (left midfielder rating)
    lcm VARCHAR(50),                                             --  (left central midfielder rating)
    cm VARCHAR(50),                                              --  (center midfielder rating)
    rcm VARCHAR(50),                                             --  (right central midfielder rating)
    rm VARCHAR(50),                                              --  (right midfielder rating)
    lwb VARCHAR(50),                                             --  (left wingback rating)
    ldm VARCHAR(50),                                             --  (left defensive midfielder rating)
    cdm VARCHAR(50),                                             --  (center defensive midfielder rating)
    rdm VARCHAR(50),                                             --  (right defensive midfielder rating)
    rwb VARCHAR(50),                                             --  (right wingback rating)
    lb VARCHAR(50),                                              --  (left back rating)
    lcb VARCHAR(50),                                             --  (left center back rating)
    cb VARCHAR(50),                                              --  (center back rating)
    rcb VARCHAR(50),                                             --  (right center back rating)
    rb VARCHAR(50),                                              --  (right back rating)
    gk VARCHAR(50),                                              --  (goalkeeper rating)
    player_face_url VARCHAR(255),                         --  (URL of the player's face image)
    club_logo_url VARCHAR(255),                           --  (URL of the club's logo)
    club_flag_url VARCHAR(255),                           --  (URL of the club's flag)
    nation_logo_url VARCHAR(255),                         --  (URL of the nation's logo)
    nation_flag_url VARCHAR(255)                          --  (URL of the nation's flag)
);