# -*- coding: utf-8 -*-
"""metadata_generation_llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mZtsEjmzPiYguh2xT1oUrDAiJ8F5_5I4
"""

# Install dependencies
!pip install transformers pandas seaborn torch --quiet

import pandas as pd
from transformers import pipeline

# Load the FIFA 22 dataset
file_path = '/content/players_22.csv'
players_22 = pd.read_csv(file_path)

# Use Hugging Face's FLAN-T5 base model
generator = pipeline("text2text-generation", model="google/flan-t5-base")

# Generate smarter column descriptions using sample values
column_descriptions = {}

for col in players_22.columns:
    # Get sample values for better context
    sample_values = players_22[col].dropna().astype(str).unique()[:20]
    sample_str = ", ".join(sample_values)

    prompt = f"""You are analyzing a football dataset from FIFA 22.
Column Name: '{col}'
Sample Values: {sample_str}
Describe what this column likely represents in one or two sentences."""

    try:
        result = generator(prompt, max_length=50, do_sample=True)[0]['generated_text']
        column_descriptions[col] = result
    except Exception as e:
        column_descriptions[col] = f"Error: {e}"

# Print out results
for col, desc in column_descriptions.items():
    print(f"{col}:")
    print(desc)
    print("-" * 60)

# Save to a file
output_file = "players_22_column_descriptions.txt"
with open(output_file, "w") as f:
    for col, desc in column_descriptions.items():
        f.write(f"Column: {col}\n")
        f.write(f"Description: {desc}\n")
        f.write("-" * 60 + "\n")

print(f"\n Column descriptions saved to {output_file}")